In [52]:
import pandas as pd
import numpy as np
df = pd.read_csv('Titanic-Dataset.csv')

### Q_1: Split the Titanic DataFrame df into two parts: df1 (first 500 rows) and df2 (remaining rows). Concatenate them vertically to recreate the original DataFrame.

In [2]:
df_1 = df.loc[:500]
df_2 = df.loc[501:]
pd.concat([df_1,df_2])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Q_2: Create a new DataFrame passenger_details with columns PassengerId and Nationality. Perform a left join to merge it with df, keeping all original passengers.

In [ ]:

passenger_details = pd.DataFrame({ 'PassengerId': range(1,892),
                     'Nationality':'Egypt' 
                       })


merged= pd.merge(df ,passenger_details  , on="PassengerId" , how="left") 
print(merged)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked       Date Nationality
0        0         A/5 21171   7.2500   NaN        S 1912-04-10       Egypt
1        0          PC 17599  71.2833   C85        C 1912-04-11       Egypt
2        0  STON/O2. 3101282   7.9250   NaN        S 1912-04-12       Egypt
3        0            113803  53.1000  C123        S 1912-04-13       Egypt
4        0            373450   8.0500   NaN        S 1912-04-14       Egypt
..     ...               ...      ...   ...      ...        ...         ...
886      0            211536  13.0000   NaN        S 1914-09-13       Egypt
887      0            112053  30.0000   B42        S 1914-09-14       Egypt
888      2        W./C. 6607  23.4500   NaN        S 1914-09-15       Egypt
889      0            111369  30.0000  C148        C 1914-09-16       Egypt
890      0            370376   7.7500   NaN        Q 1914-09-17       Egypt

[891 rows x 14 columns]

### Q_3 : Group the data by Pclass and Sex, then calculate the average Age and total Fare for each group.

In [28]:
""" average = df.groupby(['Pclass','Sex'])['Age'].mean()
total = df.groupby(['Pclass','Sex'])['Fare'].sum()
print(average, total) """

group = df.groupby(['Pclass','Sex']).agg(
    average =('Age', 'mean'),
    total = ('Fare', 'sum')
)
print(group)

                 average      total
Pclass Sex
1      female  34.611765  9975.8250
       male    41.281386  8201.5875
2      female  28.722973  1669.7292
       male    30.740707  2132.1125
3      female  21.750000  2321.1086
       male    26.507589  4393.5865

### Q_4: Create a pivot table showing the survival rate (mean of Survived) for each combination of Sex and Pclass.

In [ ]:
#aggfunc = mean by difult
df.pivot_table('Survived' , index='Pclass' , columns='Sex' )

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

#### Q_5: Add a synthetic Date column with dates starting from 1912-04-10 (one day per passenger). Convert it to datetime and compute the monthly survival count.

In [57]:
#df.info()
"""df['Date'] = pd.date_range('1912-04-10' ,periods=891 , freq='D' )
df_4 = pd.to_datetime(df['Date'])
df['Survived'].count"""

#df['Date'] = pd.date_range('1912-04-10' ,periods=891 , freq='D' )
df['Date'] = pd.date_range('1912-04-10' ,periods=891 , freq='D' )
df_4 = pd.to_datetime(df['Date'])
survived = df[df['Survived']==1].count
print(survived)

<bound method DataFrame.count of      PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
875          876         1       3
879          880         1       1
880          881         1       2
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch            Ticket     Fare Cabin Embarked       Date
1        0          PC 17599  71.2833   C85        C 1912-04-11
2        0  STON/O2. 3101282   7.9250   NaN        S 1912-04-12
3        0            113803  53.1000  C123        S 1912-04-13
8        2            347742  11.1333   NaN        S 1912-04-18
9        0            237736  30.0708   NaN        C 1912-04-19
..     ...               ...      ...   ...      ...        ...
875      0              2667   7.2250   NaN        C 1914-09-02
879      1             11767  83.1583   C50        C 1914-09-06
880      1            230433  26.0000   NaN        S 1914-09-07
887      0            112053  30.0000   B42        S 1914-09-14
889      0            111369  30.0000  C148        C 1914-09-16

[342 rows x 13 columns]>