In [2]:
import pandas as pd
df = pd.read_csv('Titanic-Dataset.csv')

### Q_1: Create a Pandas Series named survival_series using the Survived column of the DataFrame

In [3]:
survival_series = pd.Series(df['Survived'])
print(survival_series)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

### Q_2: Display the last 3 rows of the DataFrame and check the data type of the Age column

In [4]:
DataType = df['Age'].dtype
print(DataType)
df.tail(3)

float64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### Q_3 : Select the Name and Age columns, then filter rows where the passenger’s age is greater than 30

In [5]:
filtered_rows = df.loc[df['Age']>=30,['Name','Age']]
print(filtered_rows)

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
6                              McCarthy, Mr. Timothy J  54.0
11                            Bonnell, Miss. Elizabeth  58.0
..                                                 ...   ...
873                        Vander Cruyssen, Mr. Victor  47.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
881                                 Markun, Mr. Johann  33.0
885               Rice, Mrs. William (Margaret Norton)  39.0
890                                Dooley, Mr. Patrick  32.0

[330 rows x 2 columns]

### Q_4: Add a new column FamilySize to the DataFrame, calculated as SibSp + Parch + 1 (including the passenger themselves)

In [6]:
df['FamilySize'] = df['SibSp']+df['Parch']+1
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,1
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,5
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,3
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2

#### Q_5: Fill missing values in the Age column with the mean age then Group the data by Pclass and calculate the average age for each class

In [8]:
df.describe()
df['Age'] = df['Age'].fillna(29.699118)
print(df['Age'])

group_data = df.groupby('Pclass')[['Age']].mean()
group_data

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

              Age
Pclass
1       37.048118
2       29.866958
3       26.403259

#### Q_Bonus: Calculate the survival rate (mean of Survived) for each gender (Sex)

In [9]:
df.pivot_table(values='Survived' , index=['Sex'], aggfunc='mean')

        Survived
Sex
female  0.742038
male    0.188908